#!/bin/bash

tabster &
TABSTER_PID=$!

while [ ! -p /tmp/tabster$TABSTER_PID ]; do
  sleep 0.1
done

if [ -f /home/mark/.local/share/uzbl/tabster.sess ]; then
    cat /home/mark/.local/share/uzbl/tabster.sess > /tmp/tabster$TABSTER_PID
else
    echo "new uzbl -s %d" > /tmp/tabster$TABSTER_PID
fi

sleep 1

wait $TABSTER_PID