#!/bin/bash

xdd=${XDG_CONFIG_HOME:-${HOME}/.config}/tabster/

tabster &
TABSTER_PID=$!

while [ ! -p /tmp/tabster$TABSTER_PID ]; do
  sleep 0.1
done

if [ ! -d ${xdd} ]; then
    mkdir -p $xdd
fi

if [ -f ${xdd}tabster.sess ]; then
    cat ${xdd}tabster.sess > /tmp/tabster$TABSTER_PID
else
    echo "new reuzbl -s %d" > /tmp/tabster$TABSTER_PID
fi

sleep 1

wait $TABSTER_PID